// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/priceMonitorpb/priceMonitor.proto

package priceMonitorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string       `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Images               string       `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	History              []*PriceTime `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	CreatedAt            string       `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name                 string       `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Product) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *Product) GetHistory() []*PriceTime {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PriceTime struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceTime) Reset()         { *m = PriceTime{} }
func (m *PriceTime) String() string { return proto.CompactTextString(m) }
func (*PriceTime) ProtoMessage()    {}
func (*PriceTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{1}
}

func (m *PriceTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceTime.Unmarshal(m, b)
}
func (m *PriceTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceTime.Marshal(b, m, deterministic)
}
func (m *PriceTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceTime.Merge(m, src)
}
func (m *PriceTime) XXX_Size() int {
	return xxx_messageInfo_PriceTime.Size(m)
}
func (m *PriceTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceTime.DiscardUnknown(m)
}

var xxx_messageInfo_PriceTime proto.InternalMessageInfo

func (m *PriceTime) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PriceTime) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type AddProductRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{2}
}

func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AddProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResponse) Reset()         { *m = AddProductResponse{} }
func (m *AddProductResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductResponse) ProtoMessage()    {}
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{3}
}

func (m *AddProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResponse.Unmarshal(m, b)
}
func (m *AddProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResponse.Marshal(b, m, deterministic)
}
func (m *AddProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResponse.Merge(m, src)
}
func (m *AddProductResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductResponse.Size(m)
}
func (m *AddProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResponse proto.InternalMessageInfo

func (m *AddProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{4}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{5}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{6}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

type ProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductsResponse) Reset()         { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()    {}
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_895da93d8286775d, []int{7}
}

func (m *ProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductsResponse.Unmarshal(m, b)
}
func (m *ProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductsResponse.Marshal(b, m, deterministic)
}
func (m *ProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductsResponse.Merge(m, src)
}
func (m *ProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ProductsResponse.Size(m)
}
func (m *ProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductsResponse proto.InternalMessageInfo

func (m *ProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "priceMonitor.Product")
	proto.RegisterType((*PriceTime)(nil), "priceMonitor.PriceTime")
	proto.RegisterType((*AddProductRequest)(nil), "priceMonitor.AddProductRequest")
	proto.RegisterType((*AddProductResponse)(nil), "priceMonitor.AddProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "priceMonitor.GetProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "priceMonitor.ProductResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "priceMonitor.GetProductsRequest")
	proto.RegisterType((*ProductsResponse)(nil), "priceMonitor.ProductsResponse")
}

func init() {
	proto.RegisterFile("services/priceMonitorpb/priceMonitor.proto", fileDescriptor_895da93d8286775d)
}

var fileDescriptor_895da93d8286775d = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0xe5, 0x4b, 0x06, 0x83, 0x30, 0xa2, 0x36, 0x24, 0x68, 0xb3, 0xc6, 0x84, 0x78, 0x80,
	0x80, 0xf1, 0x07, 0x40, 0x42, 0x3c, 0x69, 0x00, 0x3d, 0x79, 0x31, 0xa5, 0xdd, 0xe8, 0x26, 0x96,
	0xd6, 0xdd, 0xc5, 0xc4, 0xdf, 0xe0, 0x2f, 0xf1, 0x5f, 0x1a, 0xb6, 0x5b, 0xfa, 0x01, 0x9c, 0xbc,
	0xcd, 0xbc, 0xbe, 0x7d, 0x6f, 0xe6, 0x75, 0x17, 0x6e, 0x04, 0xe5, 0x5f, 0xcc, 0xa5, 0xa2, 0x1f,
	0x72, 0xe6, 0xd2, 0x87, 0x60, 0xc9, 0x64, 0xc0, 0xc3, 0x45, 0xa6, 0xed, 0x85, 0x3c, 0x90, 0x01,
	0x1e, 0xa5, 0x31, 0xf2, 0x6b, 0x40, 0x65, 0xca, 0x03, 0x6f, 0xe5, 0x4a, 0xac, 0x83, 0xc9, 0x3c,
	0xcb, 0xb0, 0x8d, 0x6e, 0x75, 0x6e, 0x32, 0x0f, 0x1b, 0x50, 0x58, 0xf1, 0x0f, 0xcb, 0x54, 0xc0,
	0xba, 0xc4, 0x33, 0x28, 0x33, 0xdf, 0x79, 0xa3, 0xc2, 0x2a, 0x28, 0x50, 0x77, 0x38, 0x80, 0xca,
	0x3b, 0x13, 0x32, 0xe0, 0xdf, 0x56, 0xd1, 0x2e, 0x74, 0x6b, 0xc3, 0xf3, 0x5e, 0xc6, 0x79, 0xba,
	0x6e, 0x9e, 0x99, 0x4f, 0xe7, 0x31, 0x0f, 0x3b, 0x00, 0x2e, 0xa7, 0x8e, 0xa4, 0xde, 0xab, 0x23,
	0xad, 0x92, 0x92, 0xab, 0x6a, 0x64, 0x24, 0x11, 0xa1, 0xb8, 0x74, 0x7c, 0x6a, 0x95, 0xd5, 0x07,
	0x55, 0x93, 0x3b, 0xa8, 0x6e, 0x84, 0xb0, 0x05, 0x25, 0x65, 0xa1, 0xe7, 0x8d, 0x9a, 0xf5, 0x31,
	0xc9, 0x7c, 0xaa, 0x67, 0x56, 0x35, 0xb9, 0x86, 0xe6, 0xc8, 0xf3, 0xf4, 0x92, 0x73, 0xfa, 0xb9,
	0xa2, 0x42, 0xc6, 0xbb, 0x19, 0x9b, 0xdd, 0xc8, 0x04, 0x30, 0x4d, 0x13, 0x61, 0xb0, 0x14, 0x14,
	0xfb, 0x50, 0x09, 0x23, 0x48, 0x71, 0x6b, 0xc3, 0xd3, 0xfc, 0x66, 0x11, 0x3f, 0x66, 0x91, 0x2b,
	0x68, 0xde, 0x53, 0x99, 0x73, 0xcb, 0x25, 0x4b, 0xc6, 0x70, 0xfc, 0x6f, 0xa3, 0x16, 0x60, 0x62,
	0x24, 0xb4, 0x13, 0x99, 0x40, 0x23, 0x81, 0xb4, 0xf4, 0x00, 0x0e, 0xf5, 0x21, 0x61, 0x19, 0xea,
	0xf7, 0xec, 0xd1, 0xde, 0xd0, 0x86, 0x3f, 0x26, 0x9c, 0x4c, 0x53, 0x94, 0xa7, 0xe8, 0x7e, 0xe1,
	0x0c, 0x20, 0x09, 0x09, 0x2f, 0xb3, 0x32, 0x5b, 0x29, 0xb7, 0xed, 0xfd, 0x84, 0x68, 0x36, 0x72,
	0x80, 0x8f, 0x00, 0xc9, 0x1e, 0x79, 0xc9, 0xad, 0x28, 0xdb, 0x9d, 0xdd, 0xa3, 0x27, 0x7a, 0x33,
	0xa8, 0xa5, 0x72, 0x41, 0x7b, 0x9f, 0x60, 0x1c, 0x59, 0xfb, 0x62, 0xa7, 0xa2, 0x48, 0x24, 0xc7,
	0x8d, 0x97, 0x7a, 0xf6, 0x5d, 0x2d, 0xca, 0xea, 0x2d, 0xdd, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x49, 0x1b, 0x06, 0xd2, 0x79, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PriceMonitorServiceClient is the client API for PriceMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceMonitorServiceClient interface {
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
}

type priceMonitorServiceClient struct {
	cc *grpc.ClientConn
}

func NewPriceMonitorServiceClient(cc *grpc.ClientConn) PriceMonitorServiceClient {
	return &priceMonitorServiceClient{cc}
}

func (c *priceMonitorServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/priceMonitor.PriceMonitorService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceMonitorServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/priceMonitor.PriceMonitorService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceMonitorServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	out := new(ProductsResponse)
	err := c.cc.Invoke(ctx, "/priceMonitor.PriceMonitorService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceMonitorServiceServer is the server API for PriceMonitorService service.
type PriceMonitorServiceServer interface {
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error)
	GetProducts(context.Context, *GetProductsRequest) (*ProductsResponse, error)
}

// UnimplementedPriceMonitorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPriceMonitorServiceServer struct {
}

func (*UnimplementedPriceMonitorServiceServer) AddProduct(ctx context.Context, req *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedPriceMonitorServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedPriceMonitorServiceServer) GetProducts(ctx context.Context, req *GetProductsRequest) (*ProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}

func RegisterPriceMonitorServiceServer(s *grpc.Server, srv PriceMonitorServiceServer) {
	s.RegisterService(&_PriceMonitorService_serviceDesc, srv)
}

func _PriceMonitorService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceMonitorServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceMonitor.PriceMonitorService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceMonitorServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceMonitorService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceMonitorServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceMonitor.PriceMonitorService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceMonitorServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceMonitorService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceMonitorServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/priceMonitor.PriceMonitorService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceMonitorServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceMonitorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "priceMonitor.PriceMonitorService",
	HandlerType: (*PriceMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduct",
			Handler:    _PriceMonitorService_AddProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _PriceMonitorService_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _PriceMonitorService_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/priceMonitorpb/priceMonitor.proto",
}
