version: "3.7"
services:
  app:
    container_name: fabelio-product-price-monitor
    restart: always
    build: .
    ports:
      - "50051:50051"
      - "50052:50052"
    environment: 
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=27017
      - DATABASE=fabelio
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - "27017:27017"
